title: Snehalatha Tuniki # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Science Enthusiast from Loyalist College 
  <br>
  Data Engineer, TCS (Apple Inc.) 
  <br><br>
  <b>Contact:</b>
  <br><br>
  <a href="https://www.linkedin.com/in/snehalatha-tuniki/"><img src="images/linkedin.png" data-canonical-src="images/linkedin.png" width="50" height="50" /></a>
  <a href="https://github.com/snehalathatuniki"><img src="images/Github.png" data-canonical-src="images/Github.png" width="50" height="50" /></a>
  <a href="mailto: sneha.vps888@gmail.com"><img src="images/Email.png" data-canonical-src="images/Email.png" width="50" height="50" /></a>  

  
theme: jekyll-theme-Architect
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
