title: Snehalatha Tuniki # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
I'm fascinated about the evolution of decision-making, how they develop from data to information to insight to action, and how they can eventually transform the world.
<br><br>
  <b>Contact:</b>
  <br><br>
  <a href="https://www.linkedin.com/in/snehalatha-tuniki/"><img src="images/linkedin.png" data-canonical-src="images/linkedin.png" width="50" height="50" /></a>
  <a href="https://github.com/snehalathatuniki"><img src="images/Github.png" data-canonical-src="images/Github.png" width="50" height="50" /></a>
  <a href="mailto: sneha.vps888@gmail.com"><img src="images/Email.png" data-canonical-src="images/Email.png" width="50" height="50" /></a>  

  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
