title: Snehalatha Tuniki
logo: "/images/logo.png?raw=true"
description: >
  I am fascinated about the evolution of decision-making, how they develop from data to information to insight to action, 
  and how they can eventually transform the world.
  <b>Contact:</b>
  <a href="https://www.linkedin.com/in/snehalatha-tuniki/"><img src="images/linkedin.png" data-canonical-src="images/linkedin.png" width="50" height="50" /></a>
  <a href="https://github.com/snehalathatuniki"><img src="images/Github.png" data-canonical-src="images/Github.png" width="50" height="50" /></a>
  <a href="#" onclick="showContactForm()"><img src="images/Email.png" data-canonical-src="images/Email.png" width="50" height="50" /></a>

theme: jekyll-theme-minimal
google_analytics: UA-000000-0
contact_form_endpoint: "https://formspree.io/f/meqbvzva"
